### ISSUE TITLE
Works on Teensy 3.5

### ISSUE THREAD

**Issue by ernestum** [moretticb/Neurona#1]
When I overclock it to 168 MHz and crank up the optimizations, it runs my 16x100x5x5 network with linear activation just fine with a forward pass in 2.3ms :-)

**Comment by moretticb** [comment]
Sorry for the huge delay and thank you very much for letting me know! Would you like to contribute with a documentation of the whole process? If so, please make a pull request to enhance the readme file, and I will also update the Neurona website. I would be very happy to give you the due credits :)
